require('base')
require('highlights')
require('maps')
require('plugins')

vim.cmd('color ofirkai')
vim.cmd('set nocursorline')
vim.cmd('set t_Co=256')
vim.cmd('set colorcolumn=80')
vim.cmd('highlight CursorColumn guibg=#404040')
